In [ ]:
# preliminary-analysis-2023-load-minute-level-data.ipynb
#
# 2023/8/3
#
# Bryan Daniels
#
# Example loading 1-minute data from 2018 dataset and 5-minute data from 2019 dataset.

In [1]:
import pandas as pd

# load 1-minute data from 2018 dataset

In [5]:
data_directory = "../Data/220422/zenodo/df_day1min_alldays/"
df = pd.read_hdf(data_directory+'df_day1min_04.hdf')

In [7]:
df.columns

Index(['Age', 'Num. observations', 'Honey', 'Brood care', 'Pollen',
       'Dance floor', 'Other', 'Frame 0', 'Frame 1', 'Frame 2', 'Frame 3',
       'Frame 4', 'Frame 5', 'Median speed', 'Speed IQR',
       'Speed 90th quantile', 'Dispersion (avg)', 'Exit distance (median)',
       'Fraction squares visited', 'Day number', 'Festoon', 'Empty comb',
       'blank1', 'blank2', 'Bee unique ID', 'Cohort ID', 'Num. outside trips',
       'Num. dance floor visits', 'Dispersion-minute avg.',
       'Frame 0 - Num. crossings', 'Frame 1 - Num. crossings',
       'Frame 2 - Num. crossings', 'Frame 3 - Num. crossings',
       'Frame 4 - Num. crossings', 'Frame 5 - Num. crossings', 'timedivision'],
      dtype='object')

In [23]:
df[df['Bee unique ID']==1261][['Age','timedivision','Frame 0', 'Frame 1', 'Frame 2', 'Frame 3',
       'Frame 4', 'Frame 5']].dropna()

,Age,timedivision,Frame 0,Frame 1,Frame 2,Frame 3,Frame 4,Frame 5
249,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1323,4.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0
1860,4.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0
2397,4.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0
2934,4.0,5.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
718218,4.0,1337.0,1.0,0.0,0.0,0.0,0.0,0.0
718755,4.0,1338.0,1.0,0.0,0.0,0.0,0.0,0.0
719292,4.0,1339.0,1.0,0.0,0.0,0.0,0.0,0.0
741309,4.0,1380.0,1.0,0.0,0.0,0.0,0.0,0.0
741846,4.0,1381.0,1.0,0.0,0.0,0.0,0.0,0.0

# load 5-minute data from 2019 dataset

(1-minute data are also available on zenodo)

In [24]:
data_directory = "../Data/240329/df_day5min/"
df = pd.read_hdf(data_directory+'df_day5min_004.hdf')

In [25]:
df.columns

Index(['Age', 'Num. observations', 'Honey', 'Brood care', 'Pollen',
       'Dance floor', 'Other', 'Frame 0', 'Frame 1', 'Frame 2', 'Frame 3',
       'Frame 4', 'Frame 5', 'Median speed', 'Speed IQR',
       'Speed 90th quantile', 'Dispersion (avg)', 'Exit distance (median)',
       'Fraction squares visited', 'Day number', 'Festoon', 'Empty comb',
       'Mean x-shifted', 'Mean y', 'Bee unique ID', 'Cohort ID',
       'Num. outside trips', 'Num. dance floor visits',
       'Dispersion-minute avg.', 'Frame 0 - Num. crossings',
       'Frame 1 - Num. crossings', 'Frame 2 - Num. crossings',
       'Frame 3 - Num. crossings', 'Frame 4 - Num. crossings',
       'Frame 5 - Num. crossings', 'timedivision'],
      dtype='object')

In [29]:
df[df['Bee unique ID']==1216][['Age','timedivision','Frame 0', 'Frame 1', 'Frame 2', 'Frame 3',
       'Frame 4', 'Frame 5']].dropna()

,Age,timedivision,Frame 0,Frame 1,Frame 2,Frame 3,Frame 4,Frame 5
589,10.0,0.0,0.000000,0.519149,0.012766,0.0,0.468085,0.000000
2136,10.0,1.0,0.000000,0.000000,0.291411,0.0,0.000000,0.708589
3683,10.0,2.0,0.000000,0.000000,0.000000,0.0,0.739726,0.260274
5230,10.0,3.0,0.000000,0.203438,0.000000,0.0,0.796562,0.000000
6777,10.0,4.0,0.000000,0.987069,0.012931,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...
438390,10.0,283.0,1.000000,0.000000,0.000000,0.0,0.000000,0.000000
439937,10.0,284.0,1.000000,0.000000,0.000000,0.0,0.000000,0.000000
441484,10.0,285.0,1.000000,0.000000,0.000000,0.0,0.000000,0.000000
443031,10.0,286.0,0.994555,0.000000,0.000000,0.0,0.000000,0.005445
444578,10.0,287.0,0.995413,0.000000,0.000000,0.0,0.000000,0.004587

In [41]:
# 2026/5/15 checking bee ages with specific IDs for Shatadru
ages = []
for beeid in range(1216,2047):
    bee_ages = df[df['Bee unique ID']==beeid]['Age']
    if len(bee_ages) > 0:
        ages.append([beeid,bee_ages.iloc[0]])
ages_df = pd.DataFrame(ages,columns=['Bee unique ID','Age'])

In [43]:
ages_df.to_csv('260515_2019_day_04_bee_ages_from_5min_data.csv')